name: Haskell CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v1
        env:
          cache-name: cache-stack
        with:
          path: $HOME/.stack
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.yaml') }}-${{ hashFiles('**/stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install stack
        run: |
          mkdir -p ~/.local/bin
          export PATH=$HOME/.local/bin:$PATH
          curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      - name: Install dependencies
        run: stack --no-terminal --install-ghc test --only-dependencies
      - name: Build
        run: stack --no-terminal test --haddock --no-haddock-deps
