name: Deploying

on:
  push:
    branches: [ master, release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          podman run -it --rm -v:/workspace -w /workspace terrorjack/asterius:200811
          ahc-cabal update
          ahc-cabal build --only-dependencies --enable-tests --enable-benchmarks
          ahc-cabal build --enable-tests --enable-benchmarks all
          ahc-cabal test all
